### ISSUE TITLE
Chạy lệnh trong docker trên Windows bị lỗi 

### ISSUE THREAD

**Issue by chiphu** [dhhiep/fshare_tool#1]
Lỗi này bạn nhé:

![image](https://github.com/dhhiep/fshare_tool/assets/90211256/7842080d-e1cb-4c39-a26b-a158a8888689)

**Comment by dhhiep** [comment]
Trên window hình như nó không hiểu dấu nối dòng `\` nên bạn bỏ dấu `\` và join lại với nha nhé. 
```bash
docker run -d --name fshare_tool -p 7777:3000 -v ~/fshare_tool_dbs:/var/workspace/db/sqlite_dbs -e VLC_RC_HOST=host.docker.internal -e VLC_RC_PORT=7654 -e FSHARE_USER_EMAIL=REPLACE_YOUR_KEY@gmail.com -e FSHARE_PASSWORD=REPLACE_YOUR_KEY -e FSHARE_APP_KEY=REPLACE_YOUR_KEY -e FSHARE_USER_AGENT=REPLACE_YOUR_KEY hoanghiepitvnn/fshare_tool:latest
```

Mình sẽ update README thêm file `docker_compose.yaml` để mọi người run cho dễ hơn. Cảm ơn bạn đã báo bug.
