### ISSUE TITLE
Add feature Rclone Transfer file from Fshare to Cloud (GDrive, Dropbox .v.v.v)

### ISSUE THREAD

**Issue by chiphu** [dhhiep/fshare_tool#2]
Code của bạn xịn quá. Cảm ơn bạn rất nhiều.

Nếu có thể, bạn code thêm các tính năng upload bằng rclone với cmd này được không? 
`rclone copyurl --checksum --progress -vv "fshare direct link" drive:/"tên file"` (drive là tên ổ cloud đã auth trong file config của rclone).

Cảm ơn bạn lần nữa. Chúc vui.

**Comment by chiphu** [comment]
Thêm tùy chọn ổ cloud để upload nữa bạn nhé.

**Comment by dhhiep** [comment]
Tính năng Upload file to GG Drive/S3/NAS v.v.v via Rclone ([Providers](https://rclone.org/#providers))

---
1. Phần auth thì dùng `rclone file config` mình nghĩ là ok
2. Phần progress hiện tại cũng đã trích xuất được thông tin cần thiết
```ruby
command = 'rclone copyurl --progress "https://download040.fshare.vn/dl/v-fj1Lyo2xgTPunpKn0604jNqdCiQw2SX2-ncS-lRDMbvnp+mEVPsb3+wendduuCWVeE31MoY6nKfCgo/The.Last.of.Us.S01E01.Episode.1.1080p.HMAX.WEB-DL.DDP5.1.Atmos.H.264-SMURF.mkv" remote:/MOVIE/Movies/"The.Last.of.Us.S01E01.Episode.1.1080p.HMAX.WEB-DL.DDP5.1.Atmos.H.264-SMURF.mkv"'

IO.popen(command) do |io|
  # Read and print each line of stdout as it becomes available
  io.each_line do |line|
    next unless line.match?('ETA')

    # * The.Last.of.Us.S01E01.….Atmos.H.264-SMURF.mkv:  0% /5.081Gi, 1.325Mi/s, 1h5Transferred:         14.203 MiB / 5.081 GiB, 0%, 1.325 MiB/s, ETA 1h5m16s
    puts line.split('Transferred:')[1].strip # => 53.953 MiB / 5.081 GiB, 1%, 1.830 MiB/s, ETA 46m54s
  end
end
```
3. Phần UI thì mình nghiên cứu thêm chắc là OK

---

Cảm ơn bạn đã quan tâm đến tool này nhé. Có gì mình sẽ lên plan để implement tính năng này

**Comment by dhhiep** [comment]
https://github.com/dhhiep/fshare_tool/pull/3
