### ISSUE TITLE
Error when open in VLC

### ISSUE THREAD

**Issue by tinhnguyenv1** [dhhiep/fshare_tool#4]
<img width="1321" alt="image" src="https://github.com/dhhiep/fshare_tool/assets/57936917/6c68509e-250a-4f13-ac34-e31d487f719b">
Mình đang gặp lỗi như hình. Khi mở qua VLC. 
Đã thử trên chrome và MS edge của windows 11, chrome ubuntu 20.4 và MacOS 14.1.

**Comment by dhhiep** [comment]
Sorry b, lâu quá mình miss email, phần này chắc liên quan đến internet á b

**Comment by dhhiep** [comment]
@tinhnguyenv1 nếu bạn còn gặp vấn đề này thì bạn re-open issue giúp mình nhé. Cảm ơn bạn nhiều

**Comment by tinhnguyenv1** [comment]
> Sorry b, lâu quá mình miss email, phần này chắc liên quan đến internet á b

Hình như mình ko có quyền reopen :D
Mình thấy các feature khác đều có ok, từ download, open, copy direct link,... mình có thử ở các điều kiện internet khác nhau.
Có phần watch là ko open được VLC, nếu copy direct link rồi mở VLC paste vào open source qua URL thì vẫn play ok.
Cái này nếu rảnh fix được thì hoàn hảo. còn tàm thời mình vẫn dùng được với những feature còn lại.
Thanks.

**Comment by dhhiep** [comment]
Cảm ơn bạn đã phản hồi,

Về VLC bạn phải enabel cái giao thức telnet thì cái app của mình mới điều khiển VLC được https://github.com/dhhiep/fshare_tool?tab=readme-ov-file#enable-vlc-telnet-remote-control

**Comment by dhhiep** [comment]
Bạn có thể test bằng mở CMD gõ `telnet localhost 7654`
- Nếu hiện như khoanh màu xanh thì okie
- Nếu hiện trong ô vuông màu đỏ thì config chưa được á

<img width="1158" alt="image" src="https://github.com/user-attachments/assets/4015707e-ff68-4842-9963-b5e288759990">

**Comment by tinhnguyenv1** [comment]
> Bạn có thể test bằng mở CMD gõ `telnet localhost 7654`
> 
> * Nếu hiện như khoanh màu xanh thì okie
> * Nếu hiện trong ô vuông màu đỏ thì config chưa được á
> 
> <img alt="image" width="1158" src="https://private-user-images.githubusercontent.com/4127518/350829438-4015707e-ff68-4842-9963-b5e288759990.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzI1NTgsIm5iZiI6MTcyMTYzMjI1OCwicGF0aCI6Ii80MTI3NTE4LzM1MDgyOTQzOC00MDE1NzA3ZS1mZjY4LTQ4NDItOTk2My1iNWUyODg3NTk5OTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMDcxMDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc0MzZhODEyMjAzYWEwZmM3Y2Y3Njc0NTc3OGYzMjVkOGU5NGFkM2M2M2UwNjg5NDFlODhmZWRiYjJjOGI2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Voz3MUKj2ENOuFkUigX0t2-tP8rrmzks7JhKUivIZkI">

ok thanks, mình build docker container quên ko config cho port này.

**Comment by dhhiep** [comment]
Cảm ơn bạn
