### ISSUE TITLE
rclone

### ISSUE THREAD

**Issue by truongbber** [dhhiep/fshare_tool#5]
bác viết được kiểu mount nguyên cái link folder vào 1 thư mục trên linux được thì ngon

**Comment by dhhiep** [comment]
Mount nguyên cái folder ý là sao bác. Tại tính năng [ Transfer file from Fshare to Cloud](https://github.com/dhhiep/fshare_tool/issues/2 ) nên chưa hiểu ý b mount folder là sao á
